select *from public."DimProducts";
select *from public."FactOrderItem";
select *from public."Fact_orders";
select *from public."FactPayments";
select *from public."DimCustomers";






-- ##Customer & Order Fundamentals 

-- 1. How many total orders has UrbanCart received so far?

select 
	count(distinct fo."Order_id") as "Total order"
	from public."Fact_orders" fo;

--2. How many unique customers have placed at least one order? 

select fo."Customer_id"
from public."Fact_orders" fo
group by fo."Customer_id"
having count(distinct fo."Order_id") >= 1;

--3. Which cities generate the highest number of orders?

select c."City",
       count(distinct o."Order_id") as total_orders
from public."DimCustomers" c
left join public."Fact_orders" o
  on o."Customer_id" = c."customer_id"
group by c."City"
order by total_orders desc
limit 1;

--4. What percentage of customers have placed more than one order? 
with customer_orders as (
    select 
        "Customer_id",
        count(distinct "Order_id") as total_orders
    from public."Fact_orders"
    group by "Customer_id"
),
summary as (
    select
        count(*) as total_customers,
        sum(case when total_orders > 1 then 1 else 0 end) as repeat_customers
    from customer_orders
)
select 
    (repeat_customers / total_customers) *100
        as repeat_customer_percentage
from summary;


-- 5. What is the monthly trend of total orders over time? 
select date_trunc('Month',"Order_date"::timestamp )::date as "Month",
count(distinct "Order_id") as "Total order"
from public."Fact_orders"
group by 1;


--6. What is the total revenue generated by UrbanCart? 

SELECT 
    SUM(p."unit_price" * f."Quantity") AS "Total revenue"
FROM public."FactOrderItem" AS f
LEFT JOIN public."DimProducts" AS p
    ON f."Product_id" = p."Product_id"
LEFT JOIN public."Fact_orders" AS d
    ON d."Order_id" = f."order_id"
   AND d."Status" = 'Completed';


--7. Which product categories contribute the most to total revenue? 

SELECT p."Category", 
    SUM(p."unit_price" * f."Quantity") AS "Total revenue"
FROM public."FactOrderItem" AS f
LEFT JOIN public."DimProducts" AS p
    ON f."Product_id" = p."Product_id"
LEFT JOIN public."Fact_orders" AS d
    ON d."Order_id" = f."order_id"
   AND d."Status" = 'Completed'
   group by 1
   order by  2 desc;



--8. Which individual products generate the highest revenue? 

SELECT p."Product_name", 
    SUM(p."unit_price" * f."Quantity") AS "Total revenue"
FROM public."FactOrderItem" AS f
LEFT JOIN public."DimProducts" AS p
    ON f."Product_id" = p."Product_id"
LEFT JOIN public."Fact_orders" AS d
    ON d."Order_id" = f."order_id"
   AND d."Status" = 'Completed'
   group by 1
   order by  2 desc;


--9. What is the average order value (AOV) and Average Basket Size? 
                              
SELECT 
    ROUND(
        SUM(p."unit_price" * f."Quantity") 
        / COUNT(DISTINCT d."Order_id")::numeric, 2
    ) AS "Average Order Value",

    ROUND(
        SUM(f."Quantity") 
        / COUNT(DISTINCT d."Order_id")::numeric, 2
    ) AS "Average Basket Size"

FROM public."FactOrderItem" AS f

LEFT JOIN public."DimProducts" AS p
    ON f."Product_id" = p."Product_id"

LEFT JOIN public."Fact_orders" AS d
    ON d."Order_id" = f."order_id"
   AND d."Status" = 'Completed';


--10. Which products are at risk of stock-out due to high sales volume and low inventory?


    SELECT 
    p."Product_id",
    p."Product_name",
    p."Stock",
    s."Total_Sales"
FROM public."DimProducts" AS p

LEFT JOIN (
    SELECT 
        f."Product_id",
        SUM(f."Quantity") AS "Total_Sales"
    FROM public."FactOrderItem" AS f
    LEFT JOIN public."Fact_orders" AS d
        ON f."order_id" = d."Order_id"
    WHERE d."Status" = 'Completed'
    GROUP BY f."Product_id"
) AS s
ON p."Product_id" = s."Product_id"

WHERE p."Stock" < 100    -- Stock threshold (adjustable)
  AND s."Total_Sales" > 10      -- Sales threshold (adjustable)
ORDER BY s."Total_Sales" DESC;



--11. Which customers contribute the highest total revenue? 

SELECT 
    c."customer_id",
    c."full_name",
    SUM(f."Quantity" * p."unit_price") AS "Total_Revenue"
FROM public."FactOrderItem" AS f

LEFT JOIN public."Fact_orders" AS o
    ON f."order_id" = o."Order_id"
   AND o."Status" = 'Completed'

LEFT JOIN public."DimProducts" AS p
    ON f."Product_id" = p."Product_id"

LEFT JOIN public."DimCustomers" AS c
    ON o."Customer_id" = c."customer_id"

GROUP BY c."customer_id", c."full_name"
ORDER BY "Total_Revenue" DESC
LIMIT 10;  -- Top 10 customers



--12. What is the average number of products purchased per order?



SELECT 
    ROUND(
        SUM(f."Quantity") 
        / COUNT(DISTINCT d."Order_id")::numeric
    , 2) AS "Average Products Per Order"
FROM public."FactOrderItem" AS f

LEFT JOIN public."Fact_orders" AS d
    ON f."order_id" = d."Order_id"
   AND d."Status" = 'Completed';


--13. Do male and female customers show different purchasing patterns by category? 

SELECT 
    c."Gender",
    p."Category",
    COUNT(DISTINCT o."Order_id") AS "Total Orders",
    SUM(f."Quantity") AS "Total Quantity",
    ROUND(SUM(f."Quantity" * p."unit_price"), 2) AS "Total Revenue"
FROM public."FactOrderItem" f

JOIN public."Fact_orders" o
    ON f."order_id" = o."Order_id"
   AND o."Status" = 'Completed'

JOIN public."DimCustomers" c
    ON o."Customer_id" = c."customer_id"

JOIN public."DimProducts" p
    ON f."Product_id" = p."Product_id"

GROUP BY 
    c."Gender",
    p."Category"

ORDER BY 
    p."Category",
    c."Gender";


--14. Which cities have the highest average order value? 


SELECT
    c."City",
    ROUND(
        SUM(ft."Quantity" * dp."unit_price") 
        / COUNT(DISTINCT o."Order_id")::numeric,
    2) AS "average_order_value"
FROM public."DimCustomers" AS c
JOIN public."Fact_orders" AS o
    ON c."customer_id" = o."Customer_id"
   AND o."Status" = 'Completed'
JOIN public."FactOrderItem" AS ft
    ON ft."order_id" = o."Order_id"
JOIN public."DimProducts" AS dp
    ON ft."Product_id" = dp."Product_id"
GROUP BY c."City"
ORDER BY "average_order_value" DESC;


--15. How does customer purchasing behavior change over time since account creation? 
SELECT
    c."customer_id",
    (EXTRACT(YEAR FROM AGE(
        o."Order_date"::timestamp, 
        c."Created_at"::timestamp
    )) * 12 
     + EXTRACT(MONTH FROM AGE(
        o."Order_date"::timestamp, 
        c."Created_at"::timestamp
    ))) AS months_since_creation,
    COUNT(DISTINCT o."Order_id") AS total_orders,
    SUM(ft."Quantity") AS total_quantity,
    ROUND(SUM(ft."Quantity" * dp."unit_price"), 2) AS total_revenue,
    ROUND(SUM(ft."Quantity" * dp."unit_price") / COUNT(DISTINCT o."Order_id"), 2) AS avg_order_value
FROM public."DimCustomers" AS c
JOIN public."Fact_orders" AS o
    ON c."customer_id" = o."Customer_id"
   AND o."Status" = 'Completed'
JOIN public."FactOrderItem" AS ft
    ON o."Order_id" = ft."order_id"
JOIN public."DimProducts" AS dp
    ON ft."Product_id" = dp."Product_id"
GROUP BY c."customer_id", months_since_creation
ORDER BY c."customer_id", months_since_creation;


--16. Which payment methods are used most frequently? 


SELECT
    o."method",
    COUNT(DISTINCT o."payment_id") AS total_payments
FROM public."FactPayments" AS o
GROUP BY
    o."method"
ORDER BY
    total_payments DESC;



--17. Is there any relationship between payment method and order status? 
SELECT fp."method",
    o."Status",
    COUNT(o."Order_id") AS total_orders
FROM public."Fact_orders" AS o
left join public."FactPayments" as fp
on fp."order_id"=o."Order_id"
GROUP BY fp."method", o."Status"
ORDER BY fp."method", o."Status";


--18. Do certain cities prefer specific payment methods? 
SELECT
    c."City",
    p."method" AS payment_method,
    COUNT(DISTINCT o."Order_id") AS total_orders
FROM public."Fact_orders" AS o

JOIN public."FactPayments" AS p
    ON o."Order_id" = p."payment_id"

JOIN public."DimCustomers" AS c
    ON o."Customer_id" = c."customer_id"

WHERE o."Status" = 'Completed'

GROUP BY 
    c."City",
    p."method"

ORDER BY 
    c."City",
    total_orders DESC;


--19. What is the average number of items per order by payment method? 

SELECT
    p."method" AS payment_method,
    ROUND(
        SUM(foi."Quantity")::numeric 
        / COUNT(DISTINCT o."Order_id"),
        2
    ) AS avg_items_per_order
FROM public."FactPayments" AS p

JOIN public."Fact_orders" AS o
    ON p."order_id" = o."Order_id"
   AND o."Status" = 'Completed'

JOIN public."FactOrderItem" AS foi
    ON o."Order_id" = foi."order_id"

GROUP BY p."method"
ORDER BY avg_items_per_order DESC;


--20 Which products are most frequently ordered together? 

SELECT
    p1."Product_name" AS product_1,
    p2."Product_name" AS product_2,
    COUNT(*) AS times_ordered_together
FROM public."FactOrderItem" f1
JOIN public."FactOrderItem" f2
    ON f1."order_id" = f2."order_id"
   AND f1."Product_id" < f2."Product_id"
JOIN public."DimProducts" p1
    ON f1."Product_id" = p1."Product_id"
JOIN public."DimProducts" p2
    ON f2."Product_id" = p2."Product_id"
GROUP BY 
    p1."Product_name",
    p2."Product_name"
ORDER BY times_ordered_together DESC
LIMIT 10;

--21. Which product pairs appear most often across all orders? 

SELECT
    p1."Product_name" AS product_1,
    p2."Product_name" AS product_2,
    COUNT(*) AS pair_frequency
FROM public."FactOrderItem" f1

JOIN public."FactOrderItem" f2
    ON f1."order_id" = f2."order_id"
   AND f1."Product_id" < f2."Product_id"

JOIN public."DimProducts" p1
    ON f1."Product_id" = p1."Product_id"

JOIN public."DimProducts" p2
    ON f2."Product_id" = p2."Product_id"

GROUP BY 
    p1."Product_name",
    p2."Product_name"

ORDER BY 
    pair_frequency DESC
LIMIT 10;



--22. Based on product co-occurrence and customer behavior, which products should 
--UrbanCart promote together to maximize cross-selling opportunities? 


SELECT
    p1."Product_name" AS product_1,
    p2."Product_name" AS product_2,
    COUNT(DISTINCT f1."order_id") AS times_ordered_together,
    ROUND(AVG(ft."Quantity" * dp."unit_price"), 2) AS avg_order_revenue
FROM public."FactOrderItem" f1
JOIN public."FactOrderItem" f2
    ON f1."order_id" = f2."order_id"
   AND f1."Product_id" < f2."Product_id"
JOIN public."FactOrderItem" ft
    ON f1."order_id" = ft."order_id"
JOIN public."DimProducts" dp
    ON ft."Product_id" = dp."Product_id"
JOIN public."DimProducts" p1
    ON f1."Product_id" = p1."Product_id"
JOIN public."DimProducts" p2
    ON f2."Product_id" = p2."Product_id"
JOIN public."Fact_orders" o
    ON f1."order_id" = o."Order_id"
   AND o."Status" = 'Completed'
GROUP BY
    p1."Product_name",
    p2."Product_name"
ORDER BY times_ordered_together DESC, avg_order_revenue DESC
LIMIT 10;

